apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcatdeployment
  labels:
    env: prod
spec:
  selector:
    matchLabels:
      app: tomcatapp
  replicas: 4
  template:
    metadata:
      labels:
        app: tomcatapp
    spec:
      containers:
      - name: tomcat
        image: dhire/java_tomcat
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
      nodeSelector:
        env: prod
        
---
apiVersion: v1
kind: Service
metadata:
  name: tomcatapp
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: tomcatapp
    
